"""Add fish_img table

Revision ID: 0c1aadbcdbd8
Revises: 
Create Date: 2025-04-16 18:20:17.823469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c1aadbcdbd8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fish_img',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=False),
    sa.Column('color_histogram', sa.PickleType(), nullable=False),
    sa.Column('hu_moments', sa.PickleType(), nullable=False),
    sa.Column('lbd', sa.PickleType(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fish_img')
    # ### end Alembic commands ###
